<img src="https://dauphine.psl.eu/fileadmin/_processed_/9/2/csm_damier_logo_Dauphine_f7b37a1ff2.jpg" width="200" style="vertical-align:middle" /> <h1>Master 222: Introduction to Python - Session 2</h1>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Zaltarba/PSL_python_for_finance/blob/main/python_session_2.ipynb)


# Remainders From Last Session

## Temperature Data Analysis

**Introduction**
You're provided with a list of temperatures (in degrees Celsius) spanning over a week:
``` python
temperatures = [20.5, 22.3, 19.8, 21.6, 23.2, 18.9, 20.2]
```
Your task is to analyze this data by developing specific functions and then interpreting the results.

**Functions to Develop**

1.   Function `average_temp()`:

*Input:* A list of temperatures.

*Task:* Calculate the average temperature for the week.

*Return:* The average temperature.

2. Function `hot_days_count()`:

*Input:* A list of temperatures.

*Task:* Determine the number of days the temperature was above 21°C.

*Return:* The count of days.

3. Function `coldest_day()`:

*Input:* A list of temperatures.

*Task:* Identify the index of the coldest day (0 for Monday, 6 for Sunday).

*Return:* The index of the day.

**Display the Results**

After you've developed and tested your functions, you should:

- Print the average temperature of the week.
- Print the number of days when the temperature was above 21°C.
- Print the coldest day of the week based on the index (e.g., "The coldest day was Wednesday...").

**Sample output**
``` python
The average temperature for the week is: 20.79°C.
There were 3 days with a temperature above 21°C.
The coldest day was Wednesday with a temperature of 18.9°C.
```

Try using a list by comprehension for question 1 and 2.  
Use a dictionary for the question 3 to map indices to days of the week.

In [12]:
temperatures = [20.5, 22.3, 19.8, 21.6, 23.2, 18.9, 20.2]
## Insert your code here

def average_temp(temperatures):
  fract_temp = [temp/len(temperatures) for temp in temperatures]
  sum_temp=0
  for i in range(len(temperatures)):
    sum_temp+=fract_temp[i]

  return sum_temp

print(f"The average temperature for the week was {average_temp(temperatures):.2f}°C.")


The average temperature for the week was 20.93°C.


In [3]:
def hot_days_count(temperatures):
  hot_days=[temp for temp in temperatures if temp>21]
  return len(hot_days)

print(f"There were {hot_days_count(temperatures)} days with a temperature above 21°C.")

There were 3 days with a temperature above 21°C.


In [9]:
def coldest_day(temperatures):
    min_temp = temperatures[0]
    coldest_index = 0
    for i in range(1, len(temperatures)):
        if temperatures[i] < min_temp:
            min_temp = temperatures[i]
            coldest_index = i
    return coldest_index

weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
days_dict = {i: weekdays[i] for i in range(len(weekdays))}

idx = coldest_day(temperatures)
print(f"The coldest day was {days_dict[idx]} with a temperature of {temperatures[idx]:.2f}°C.")

The coldest day was Saturday with a temperature of 18.90°C.


In [23]:
for i, x in enumerate(temperatures):
  print(i, x)

0 20.5
1 22.3
2 19.8
3 21.6
4 23.2
5 18.9
6 20.2


# The NumPy library

## Context and Objective

Python is an almost indispensable programming language in the world of Quantitative finance.   
It's open source, and increasingly popular.  
In this exercise, you will learn to use the NumPy module.  
NumPy is a Python package specialized in the manipulation of arrays.  
This exercise will only focus on one-dimensional arrays (vectors) and two-dimensional arrays (matrices).

[For more information on NumPy](http://www.numpy.org/)

## Prerequisite Skills

- Basic programming concepts
- Lists
- Basic linear algebra concepts

## Exercice 1

The exercise is composed of several questions.   
To begin, execute the following preamble cell:


In [13]:
import numpy as np

In Python, an array is an ordered collection of values, which can be of any type, not **only numbers**.

The `array()` method allows you to define a **one-dimensional array** from a list. Given `X` as a list of values, you can use the command `np.array(X)` to transform the list into a one-dimensional array.

1. Create an array from the list `[1,1,1,1]`

In [22]:
## Insert your code here
ones_array=np.array([1 for i in range(4)])
ones_array


array([1, 1, 1, 1])

There are commands to inquire about the variables we are manipulating. Here's a table summarizing these commands:

| Command    | Effect                                         | Example                     |
|------------|------------------------------------------------|-----------------------------|
| type(X)    | Returns the type of the variable X            | type(2) returns `<class 'int'>`      |
| np.shape(X)| Returns the dimension of the variable X       | np.shape([1,2]) returns (2,) |

By default, Numpy creates one-dimensional arrays from lists. If you want a different dimension, you should specify it using the command `np.reshape(X, new_shape)` where `X` is the array whose dimensions you want to change.

2. Create a variable *a* and assign to it an array with the list [1,2,3,4,5]
3. Verify that its dimension is indeed (5,)

In [21]:
## Insert your code here
list_1=np.array([1,2,3,4,5])
np.shape(list_1)



(5,)

Now that we've seen how to get information about arrays, we'd like to create some. There are various commands to generate one-dimensional arrays. Here's a table summarizing them:

| Command               | Meaning                                                        | Example                                    |
|-----------------------|----------------------------------------------------------------|--------------------------------------------|
| np.ones(n)            | Returns an array of dimension (n,) of 1s                        | np.ones(5) returns array([1, 1, 1, 1, 1])  |
| np.zeros(n)           | Returns an array of dimension (n,) of 0s                        | np.zeros(5) returns array([0, 0, 0, 0, 0]) |
| np.arange(n)          | Returns an array of dim(n,) of ordered numbers from 0 to n-1    | np.arange(5) returns array([0, 1, 2, 3, 4])|
| np.linspace(a,b,n)    | Returns an array of dim(n,) of n numbers evenly spaced between a and b | np.linspace(0,5,5) returns array([0, 1.25, 2.5, 3.75, 5.0])|
| np.linspace(a,b)      | Returns an array of dim(50,) of 50 numbers evenly spaced between a and b |                                            |
| np.concatenate((X,Y)) | Returns an array of dim(dimX+dimY,) resulting from the assembly of X and Y | np.concatenate((array([1]),array([0]))) returns array([1,0])|

4. Create 4 variables a, b, c, d
    - Assign to a an array with 5 zeros
    - Assign to b an array with 5 ones
    - Assign to c an array of size 10 containing 5 zeros followed by 5 ones, arranged judiciously.
    - Assign to d an array of the integers from 10 to 50.



In [32]:
## Insert your code here
a=np.zeros(5)
b=np.ones(5)
c=np.concatenate((a,b))
d=np.arange(10,51)

print(a)
print(b)
print(c)
print(d)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


5. Generate two arrays of ordered numbers from 0 to 10 (thus of size 11) using different commands.

In [50]:
## Insert your code here
a=np.arange(11)
b=np.linspace(0,10,11)
c=np.array([i for i in range(11)])

print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0  1  2  3  4  5  6  7  8  9 10]


6. Create a list `c` with numbers ranging from 0 to 10 **A list, not an array**.
    - Use the following syntax: `list(range())`.
    - Add 5 to all the terms in `c`
        - without the numpy library.
        - with the numpy library.
    - Display `c`.


In [45]:
## Insert your code here
c=[i for i in range(11)]
c=[x+5 for x in c]
print(c)

c=np.arange(11)
c+=5
print(c)


[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[ 5  6  7  8  9 10 11 12 13 14 15]


In [63]:
def f(x):
  return x**2

def calculate_integral(a,b):
  values=np.linspace(a,b,10000)
  sum_areas=0
  for i in range(9999):
    area=(values[i+1]-values[i])*f(values[i+1])
    sum_areas+=area

  return sum_areas

print(calculate_integral(0,1))


0.33338334000083325


We can perform similar operations with matrices, which are 2-dimensional arrays.

Thus, `np.ones((n, p))` returns an `NxP` matrix filled with ones, `np.zeros((n, p))` returns an `NxP` matrix filled with zeros.

`np.diag(v)` returns a matrix whose diagonal consists of the vector v.
Moreover, `np.diag(v, k)` returns a matrix where the k-th diagonal consists of the vector v, k can be positive or negative; if k is positive, the shift is to the "right," otherwise to the left.

7. Create a matrix *mat* of size 5x5 with 1s on the diagonal.

In [78]:
## Insert your code here
mat=np.diag(np.ones(5))
mat


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

We can use mathematical operators **+**, **-**, on arrays provided that the mathematical operation makes sense.

**Caution: If you use the operators '\*' or '/' you will only perform a term-by-term operation**  

8. Create a 6x6 matrix with 1s on the diagonal and on the sub-diagonal using a mathematical operator.

In [85]:
## Insert your code here
mat_1=np.diag(np.ones(6))
mat_2=np.diag(np.ones(5),-1)
mat=mat_1+mat_2
mat


array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1.]])

In [91]:
#slicing
mat[:3,1:3]

array([[0., 0.],
       [1., 0.],
       [1., 1.]])

Accessing specific elements of an array is done similarly to lists. If the array is two-dimensional, two parameters are needed.

*For example*: let X be a two-dimensional array, `X[0, 0]` returns the element located at row 1, column 1. `X[:, 0]` returns the first column. `X[0:3, 0]` returns the first three rows of the first column. This method is referred to as *slicing* in programming.

9. Create this matrix using `np.ones()`, `np.diag()` and slicing:
$$
\begin{pmatrix}
5 & 0 & 0 & 0 \\
5 & 1 & 0 & 0 \\
4 & 4 & 4 & 4 \\
5 & 0 & 0 & 1
\end{pmatrix}
$$

In [98]:
## Insert your code here
a=np.ones(4)*4
b=np.ones(4)*5

mat=np.diag(np.ones(4))
mat[:,0]=b
mat[2,:]=a
print(mat)

[[5. 0. 0. 0.]
 [5. 1. 0. 0.]
 [4. 4. 4. 4.]
 [5. 0. 0. 1.]]


10. Create a numpy array with only ones of shape N, T
11. Using slicing access create :
    - a matrix_a array with all N and T from 0 to 5
    - a matrix_b array with all N and T from T-5 to T-1

In [108]:
## Insert your code here
N, T = 8, 10

mat=np.ones((8,10))

mat_a=mat[:,0:5]
mat_b=mat[:,T-5:T-1]

print(mat)
print(mat_a)
print(mat_b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercice 2

With the Numpy module, you can create random numbers uniformly distributed between 0 and 1.   
The syntax is as follows: `np.random.rand()` to return a single draw, `np.random.rand(n)` to return a row array of n draws, and `np.random.rand(n, p)` to return an NxP matrix of uniformly distributed random draws.

1. Display a random number uniformly distributed between 0 and 1

In [178]:
## Insert your code here
np.random.rand()

0.8104912084498189

2. Display a 5x5 matrix of random numbers uniformly distributed between 0 and 1

In [184]:
## Insert your code here
print(np.random.rand(5,5))

[[0.89526097 0.79608513 0.06315561 0.59203476 0.64336434]
 [0.80408363 0.42982215 0.44144938 0.99302872 0.53307166]
 [0.02119545 0.51175377 0.1194937  0.00656874 0.89717433]
 [0.70756092 0.04880114 0.00127768 0.08545489 0.55301355]
 [0.35693436 0.74822926 0.19590813 0.67429368 0.05804307]]


3. Write a function `random_number()` that takes two integer parameters and returns a random number uniformly distributed between the two integers.
4. Call the function `random_number(10, 15)`

*Note: If $X \sim U[0,1]$, then $Y := (b-a)X + a \sim U[a,b]$*

5. Use the function np.rando.uniform to generate a similar variable

6. Write a function `random_matrix()` that takes an integer parameter N and returns a NxN matrix with 1s everywhere except on the diagonal where there are numbers uniformly distributed between 0 and 1.
7. Test for N=3 and N=5

> Example: `random_matrix(3)` should return a matrix similar to
$$
\begin{pmatrix}
0.62678954 & 1 & 1 \\
1 & 0.94077299 & 1 \\
1 & 1 & 0.29263003 \\
\end{pmatrix}
$$

In [176]:
## Insert your code here
def random_number(a,b):
  return np.random.uniform(a,b)

random_number(10,15)

14.333853567133048

In [208]:
## Insert your code here
def random_y(a,b):
  return (b-a)*np.random.uniform()+a

random_y(10,15)

10.355255147028215

In [215]:
def random_matrix(n):
  mat_1=np.ones((n,n))
  mat_2=np.diag(np.random.rand(n))
  return mat_1 - mat_2

print(random_matrix(3))



[[0.2991946  1.         1.        ]
 [1.         0.28072633 1.        ]
 [1.         1.         0.72693618]]


- In NumPy, operations can be performed between arrays and scalars.
> Example:
```
a = np.array([1, 2, 3])
a * 4 returns array([4, 8, 12])
a + 2 returns array([3, 4, 5])
```

8. Create a matrix mat_five of size 5x5 with fives on the diagonal
9. Create two matrices mat_two and mat_two_bis of size 5x5 with twos everywhere, in two different ways
    - Use a list by comprehension in one method
10. Display the matrices

In [221]:
## Insert your code here
mat_five=np.diag(np.ones(5))*5
print(mat_five)

mat_two=np.ones((5,5))*2
print(mat_two)

mat_two_bis=np.array([[2 for _ in range(5)] for _ in range(5)])
print(mat_two_bis)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In NumPy, operations between arrays are performed element-wise by default.

> Example:
```
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b returns array([4, 10, 18])
```

To perform matrix multiplication in the mathematical sense, the following syntax is used: np.dot(X,Y)

If the dimensions are incompatible, errors are triggered.

## Exercice 3

1. Create a matrix `mat_one` of size 5x5 with random numbers.
2. Create a matrix `mat_two` of size 5x5 with ones everywhere.
3. Create a matrix `mat_three` and assign to it the element-wise product between `mat_one` and `mat_two`
4. Create a matrix mat_four and assign to it the matrix product between `mat_one` and `mat_two`
5. Display `mat_three` and `mat_four`

In [ ]:
## Insert your code here



6. Create a matrix `a` with dimensions 5x2 with arbitrary values
7. Create another matrix `b` with dimensions 2x5 with arbitrary values
8. Return the [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)) of the two matrices here



In [ ]:
## Insert your code here


## Exercice 4

The use of logical operators is possible via NumPy.

1. Create two matrices *mat_one* and *mat_two* of size 5x5 with random values.
2. Using the operator `*` and the logical operator '`==`', return a 5x5 matrix of True.
3. Using matrix multiplication and the logical operator '`==`', return a 5x5 matrix of False.


In [226]:
## Insert your code here
mat_one=np.random.rand(5,5)
mat_two=np.random.rand(5,5)

mat_true=(mat_one * 0) == 0
mat_false=mat_one*mat_two==0

print(mat_true)
print(mat_false)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


## Exercice 5

It is possible to analyze data with NumPy. Here are some functions summarized:

| Command   | Meaning                 |
|-----------|-------------------------|
| np.mean(X) | returns the mean of X   |
| np.var(X)  | returns the variance of X|
| np.std(X)  | returns the standard deviation of X |
| X.sum()  | sums the elements of X   |
| X.prod() | multiplies the elements of X |
| X.min()  | returns the minimum of X |
| X.max()  | returns the maximum of X |

Furthermore, when working with matrices, it's possible to specify a second argument or a parameter to clarify where we are working. For example:

```
mat = np.random.rand(5, 5)
np.mean(mat, axis = 0)  ## returns the mean of the rows
np.mean(mat, axis = 1) ## returns the mean of the columns
mat.sum(axis = 0) ## returns the sum of the rows
```

1. Verify that the mean of a uniformly distributed law on [0,1] is close to 0.5 for a large number of draws.

**Note:**

*As the number of draws increases, the mean value of the uniformly distributed random values should converge to 0.5 according to the Law of Large Numbers.*

In [ ]:
## Insert your code here
uniform_array=np.random.rand(10000)
mean=uniform_array.mean()
print(mean)

2. Approximate $\pi$ using the folowing equation, using only Numpy methods and a function
$$
\frac{\pi}2=\prod_{n=1}^{\infty}\frac{4n^2}{4n^2-1}
$$
```python
def pi_approximation(n)
    ...
    return approx
```

3. Compare using `np.math.pi` for different values of n using

```python
from tqdm import tqdm
for n in tqdm(range(1, 100, 10)):
```

In [ ]:
## Insert your code here


## To go further..

**Exercise :**
- Create a 3x3 matrix with values ranging from 0 to 8 using `np.reshape`.
- Create a 3x3 identity matrix with a built in numpy function.
- Use indexing to replace the top row of the identity matrix with 9s. Make sure not to modify the initial matrix.

**Exercise :**
- Generate a random array of size 25, folowing a normal distribution. Find its mean.
- Generate a random matrix of size 5x5. Find the sum of all the elements, the sum of the columns, and the sum of the rows.

**Exercise :**
- Create an array of 10 random numbers. Replace all the values less than 0.5 with 0.

**Exercise :**
- Using np.random.uniform estimate the value of pi.

**Hint:** Use the probability of a random point $X = (x_1, x_2)$ with $X \in [-1, 1]^2$ to belong to the unit circle.

**Exercise :**

This exercie aims to illustrate the difference in computation between Python `list` and `NumPy` arrays.

1. Create a Python `my_list` of 100 000 integers using `range`.
2. Create a Python `my_array` of 100 000 integers using `np.arange`.
3. Compute the sum of all elements:
   - Using the built-in `sum()` function on the Python list.
   - Using the `np.sum()` function on the NumPy array.
4. Compare the execution times of the two approaches.

**Hint:** Use the `%timeit` magic command in a Jupyter notebook or the `time` module in Python to measure performance (only when computing the sum).

``` python
%timeit sum(py_list)
```

In [ ]:
## Insert your code here
